package test.domain;

public class Test {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST.TE00
     *
     * @mbggenerated
     */
    private Long te00;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST.TE01
     *
     * @mbggenerated
     */
    private String te01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST.TE02
     *
     * @mbggenerated
     */
    private String te02;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST.TE03
     *
     * @mbggenerated
     */
    private String te03;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST.TE00
     *
     * @return the value of TEST.TE00
     *
     * @mbggenerated
     */
    public Long getTe00() {
        return te00;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST.TE00
     *
     * @param te00 the value for TEST.TE00
     *
     * @mbggenerated
     */
    public void setTe00(Long te00) {
        this.te00 = te00;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST.TE01
     *
     * @return the value of TEST.TE01
     *
     * @mbggenerated
     */
    public String getTe01() {
        return te01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST.TE01
     *
     * @param te01 the value for TEST.TE01
     *
     * @mbggenerated
     */
    public void setTe01(String te01) {
        this.te01 = te01 == null ? null : te01.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST.TE02
     *
     * @return the value of TEST.TE02
     *
     * @mbggenerated
     */
    public String getTe02() {
        return te02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST.TE02
     *
     * @param te02 the value for TEST.TE02
     *
     * @mbggenerated
     */
    public void setTe02(String te02) {
        this.te02 = te02 == null ? null : te02.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST.TE03
     *
     * @return the value of TEST.TE03
     *
     * @mbggenerated
     */
    public String getTe03() {
        return te03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST.TE03
     *
     * @param te03 the value for TEST.TE03
     *
     * @mbggenerated
     */
    public void setTe03(String te03) {
        this.te03 = te03 == null ? null : te03.trim();
    }
}